apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: stg
spec:
  ports:
  - nodePort: 30007
    port: 3000
    targetPort: 3000
  selector:
    app: front
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: stg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - image: 819145822531.dkr.ecr.ap-northeast-2.amazonaws.com/devops/front:v20240502-2006
        name: front
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "200"
            memory: 256Mi
          requests:
            cpu: "100"
            memory: 128Mi
