name: 'service cicd'

on:
  push:
    tags:
      - v**

env:
  GITHUB_REPOSITORY: devops/front
  AWS_REGION: ap-northeast-2
  DEPLOY_ENV: stg

jobs:
  build:
    runs-on: dj-self
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t devops-front:${{ github.ref_name }} .
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}         
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag Docker image
        run: docker tag devops-front:${{ github.ref_name }} ${{ steps.login-ecr.outputs.registry }}/${{ env.GITHUB_REPOSITORY}}:${{ github.ref_name }}

      - name: Push Docker image to Amazon ECR
        run: docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.GITHUB_REPOSITORY}}:${{ github.ref_name }}

      - name: Build kustomize
        run: |
          cd manifests/overlays/stg
          cd deploys/
          rm  *.yaml
          cd ..
          kustomize edit set image IMAGE_NAME=${{ steps.login-ecr.outputs.registry }}/${{ env.GITHUB_REPOSITORY}}:${{ github.ref_name }}
          kustomize build . > deploys/${{ env.DEPLOY_ENV}}-${{ github.ref_name }}.yaml
          
      
      - name: Set config
        run: |
          git config --local user.email "fjrzl2017@naver.com"
          git config --local user.name "dongdongjuhahaha"
          git add .
          git commit -m "[deploy] ${{ env.DEPLOY_ENV}}-${{ github.ref_name }}.yaml "
      
      - name: Push changes to main branch # merge 내용들을 main 브랜치로 최종 push
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.ACTION_TOKEN }}