name: 'Handle new issue'

on:
  push:
    tags:
      - v.**

jobs:
  build:
    runs-on: dj-self
    steps:
      - name: build
        uses: wow-actions/potential-duplicates@v1.0.8
        with:
          GITHUB_TOKEN: ${{ github.token }}
          label: duplicate
          comment: >
            Potential duplicates: {{#issues}}
              - #{{ number }} _({{ accuracy }}% Match)_
            {{/issues}}
