name: 'service cicd'

on:
  push:
    tags:
      - v.**

jobs:
  build:
    runs-on: dj-self
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build, tag
        run: |
          docker build -t my-nextjs-app .

      - name: run docker image
        run: |
          docker run -d -p 3000:3000 my-nextjs-app
