name: 'Handle new issue'

on:
  push:
    tags:
      - v.**

jobs:
  build:
    runs-on: dj-self
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: echo
        run: |
          echo "hello"

      # - name: Build, tag, and push image to Amazon ECR # 이미지 빌드하고 ECR push
      #   id: build-image
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #   # 아래처럼 docker 커맨드를 실행한다.
      #   run: |
      #     docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
      #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
      #     echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:latest"
