name: 'service cicd'

on:
  push:
    tags:
      - v**

env:
  GITHUB_REPOSITORY: 'devops/front'

jobs:
  build:
    runs-on: dj-self
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker buildx build --file Dockerfile --tag devops-front:latest --tag devops-front:${{ github.ref }} .
    
      - name: Log into Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag Docker image
        run: docker tag devops-front:${{ github.ref }} ${{ steps.login-ecr.outputs.registry }}/$GITHUB_REPOSITORY:${{ github.ref }}

      - name: Push Docker image to Amazon ECR
        run: docker push ${{ steps.login-ecr.outputs.registry }}/$GITHUB_REPOSITORY:${{ github.ref }}

